version: "3"

services:
  web:
    container_name: bulk-server
    image: eunsxx/bulk-server
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env.prod
volumes:
  app: