version: "3"

services:
  web:
    container_name: bulk-server
    image: eunsxx/bulk-server
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - type: bind
        source: /home/ubuntu/app/application.yml
        target: /app/application.yml
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CONFIG_LOCATION=/app/application.yml
    env_file:
      - .env.prod
volumes:
  app: